apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: backend.default.svc.cluster.local
  namespace: default
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /weatherforecast
    name: GET /weatherforecast
  #   isRetryable: true
  # retryBudget:
  #   retryRatio: 0.2
  #   minRetriesPerSecond: 10
  #   ttl: 10s