# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 80
  backend:
    image: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 80